# Generated by Django 5.2 on 2025-05-07 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('primerApellido', models.CharField(max_length=30)),
                ('segundoApellido', models.CharField(max_length=30)),
                ('aniosExperiencia', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('primerApellido', models.CharField(max_length=30)),
                ('segundoApellido', models.CharField(max_length=30)),
                ('cedula', models.IntegerField(unique=True)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadesDoctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevancia', models.IntegerField(default=1)),
                ('doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctores')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidades')),
            ],
        ),
        migrations.AddField(
            model_name='doctores',
            name='especialidades',
            field=models.ManyToManyField(related_name='doctores', through='api.EspecialidadesDoctores', to='api.especialidades'),
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=200)),
                ('doctores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctores')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
            ],
        ),
    ]
